name: OpenWeatherMap 
on:
  workflow_dispatch: 

jobs:
  weather-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Construir proyecto
        run: dotnet build --configuration Release

      - name: Ejecutar aplicaci√≥n con secreto
        run: dotnet run --project WeatherApp
        env:
          OPENWEATHERMAP_APIKEY: ${{ secrets.OPENWEATHERMAP_APIKEY }}
