name: Enviar saludo
on:
  workflow_dispatch

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar saludo
        run: echo "Hola desde la clase Github actions"

      - name: Mostrar ubicaci√≥n
        run : pwd
